name = "FlightMechanicsSimulator"
uuid = "f4210329-0d58-4a8c-9620-f0228abde670"
authors = ["Alex Saez <saezm.alex@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FlightMechanicsUtils = "0ddfa1e6-9159-4d5a-8b9e-3a0591f1f4a7"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CSV = "0.7, 0.8"
DataFrames = "0.21, 0.22"
FlightMechanicsUtils = "0.1"
NLsolve = "4.4"
OrdinaryDiffEq = "5.50"
StaticArrays = "1.0"
julia = "1.5"
